[package]
name = "vtk-common-execution-model"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Port of VTK::CommonExecutionModel."

[dependencies]
vtk-common-core = { path = "../vtk-common-core" }
vtk-common-data-model = { path = "../vtk-common-data-model" }
vtk-common-misc = { path = "../vtk-common-misc" }
vtk-common-system = { path = "../vtk-common-system" }
