[workspace]
resolver = "3"
members = [
    "crates/vtk-common-core",
    "crates/vtk-common-math",
    "crates/vtk-common-system",
    "crates/vtk-common-transforms",
    "crates/vtk-common-misc",
    "crates/vtk-common-data-model",
    "crates/vtk-common-execution-model",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false
